# Default values for tekton.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

tektonNamespace: tekton

namespacePermissions:
  user: pipeline
  role: edit

app:
  name: quarkus-super-heroes
  namespace: kafka
  repo:
    source:
      url: https://github.com/oliveira-shiai/quarkus-super-heroes-deploy.git
      revision: main
      #user: user1
      #password: openshift
    gitops:
      url: https://github.com/oliveira-shiai/quarkus-super-heroes
      revision: main
      #user: user1
      #password: openshift
      path: "."

routeSubdomain: ""
