---
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Values.app.namespace }}
spec:
  output:
    to:
      kind: ImageStreamTag
      name: {{ .Values.app.name }}:latest
  source:
    binary: {}
    type: Binary
  strategy:
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: ubi8-openjdk-17:1.12
        namespace: openshift
    type: Source
