---
apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: quarkus-pipeline
  namespace: {{ .Values.tektonNamespace }}
spec:
  params:
  - name: APP_NAME
    type: string
    description: The application deployment name
    default: {{ .Values.app.name }}
  - name: SOURCE_GIT_URL
    type: string
    description: The application git repository url
    default: {{ .Values.app.repo.source.url }}
  - name: SOURCE_GIT_REVISION
    type: string
    default: {{ .Values.app.repo.source.revision }}
    description: The application git repository revision
  - name: SOURCE_GIT_CONTEXT_DIR
    type: string
    default: {{ .Values.app.name }}
    description: The subdirectory in the git repository
  - name: NAMESPACE
    type: string
    description: Namespace where the buildconfig is located
    default: {{ .Values.app.namespace }}
  - name: KUSTOMIZE_GIT_URL
    type: string
    description: The kustomize git repository url
    default: {{ .Values.app.repo.gitops.url }}
  - name: KUSTOMIZE_GIT_REVISION
    type: string
    description: The kustomize git repository revision
    default: {{ .Values.app.repo.gitops.revision }}
  - name: KUSTOMIZE_GIT_CONTEXT_DIR
    type: string
    description: The subdirectory in the kustomize git repository
    default: {{ .Values.app.repo.gitops.path }}/{{ .Values.app.name }}

  workspaces:
  - name: app-source
  - name: maven-settings

  tasks:

  - name: git-clone
    taskRef:
      kind: ClusterTask
      name: git-clone
    params:
    - name: url
      value: $(params.SOURCE_GIT_URL)
    - name: revision
      value: $(params.SOURCE_GIT_REVISION)
    - name: deleteExisting
      value: 'true'
    workspaces:
    - name: output
      workspace: app-source

  - name: build-maven
    runAfter:
    - git-clone
    taskRef:
      kind: ClusterTask
      name: maven
    params:
    - name: MAVEN_IMAGE
      value: registry.access.redhat.com/ubi9/openjdk-17:1.17
    - name: CONTEXT_DIR
      value: $(params.SOURCE_GIT_CONTEXT_DIR)
    - name: GOALS
      value:
      - clean
      - compile
      - package
      - -DskipTests
      - -Dquarkus.package.type=uber-jar
    workspaces:
    - name: source
      workspace: app-source
    - name: maven-settings
      workspace: maven-settings

  - name: build-image
    runAfter:
    - build-maven
    taskRef:
      kind: Task
      name: s2i-binary
    params:
    - name: FROM_FILE
      value: $(params.SOURCE_GIT_CONTEXT_DIR)/target/$(params.APP_NAME)-1.0-runner.jar
    - name: NAMESPACE
      value: $(params.NAMESPACE)
    - name: BUILDCONFIG
      value: $(params.APP_NAME)
    workspaces:
    - name: source
      workspace: app-source

  - name: generate-tag
    runAfter:
    - build-maven
    taskRef:
      kind: Task
      name: generate-tag

  - name: tag-image
    runAfter:
    - build-image
    - generate-tag
    taskRef:
      kind: ClusterTask
      name: openshift-client
    params:
    - name: SCRIPT
      value: >-
        oc tag
        $(params.NAMESPACE)/$(params.APP_NAME):latest
        $(params.NAMESPACE)/$(params.APP_NAME):$(tasks.generate-tag.results.image-tag)

  - name: update-image
    runAfter:
    - tag-image
    taskRef:
      kind: Task
      name: update-kustomize-repo
    params:
    - name: gitRepositoryUrl
      value: $(params.KUSTOMIZE_GIT_URL)
    - name: gitRepositoryRevision
      value: $(params.KUSTOMIZE_GIT_REVISION)
    - name: gitPath
      value: $(params.KUSTOMIZE_GIT_CONTEXT_DIR)
    - name: image
      value: image-registry.openshift-image-registry.svc:5000\/$(params.NAMESPACE)\/$(params.APP_NAME)
    - name: imageTag
      value: $(tasks.generate-tag.results.image-tag)
    - name: verbose
      value: 'true'
