---
apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  namespace: {{ .Values.tektonNamespace }}
  generateName: quarkus-pipeline-
spec:
  pipelineRef:
    name: quarkus-pipeline
  serviceAccountName: pipeline
  workspaces:
    - name: app-source
      persistentVolumeClaim:
        claimName: workspace-app-source
    - name: maven-settings
      emptyDir: {}
