---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: update-swagger
  namespace: {{ .Values.tektonNamespace }}
  annotations:
    tekton.dev/displayName: "Update Kustomize Swagger URL in Git Repository"
spec:
  params:
  - name: gitRepositoryUrl
    description: URL of the Git repository to update
    type: string
    default: {{ .Values.app.repo.gitops.url }}
  - name: gitRepositoryRevision
    description: Branch or Tag to push the update to
    type: string
    default: {{ .Values.app.repo.gitops.revision }}
  - name: restFightsKustomization
    description: Path of the rest fights kustomization file to patch
    type: string
    default: {{ .Values.app.repo.gitops.path }}/rest-fights/kustomization.yaml
  - name: restHeroesKustomization
    description: Path of the rest heroes kustomization file to patch
    type: string
    default: {{ .Values.app.repo.gitops.path }}/rest-heroes/kustomization.yaml
  - name: restVillainsKustomization
    description: Path of the rest villains kustomization file to patch
    type: string
    default: {{ .Values.app.repo.gitops.path }}/rest-villains/kustomization.yaml
  - name: restFightsOpenapiServers
    description: The quarkus.smallrye-openapi.servers property to patch
    type: string
  - name: restHeroesOpenapiServers
    description: The quarkus.smallrye-openapi.servers property to patch
    type: string
  - name: restVillainsOpenapiServers
    description: The quarkus.smallrye-openapi.servers property to patch
    type: string
  stepTemplate:
    env:
    - name: "HOME"
      value: "/tekton/home"
  steps:
  - name: main
    image: alpine/git:v2.43.0
    workingDir: /workspace
    script: |
      #!/usr/bin/env sh
      set -eux -o pipefail

      git config --global user.email "tekton@tekton.dev"
      git config --global user.name "OpenShift Pipelines"

      git clone "$(params.gitRepositoryUrl)" repo && cd repo
      git checkout "$(params.gitRepositoryRevision)"

      sed -r "s/^(\s*quarkus.smallrye-openapi.servers\s*:\s*).*/\1$(params.restFightsOpenapiServers)/" -i ./$(params.restFightsKustomization)
      sed -r "s/^(\s*quarkus.smallrye-openapi.servers\s*:\s*).*/\1$(params.restHeroesOpenapiServers)/" -i ./$(params.restHeroesKustomization)
      sed -r "s/^(\s*quarkus.smallrye-openapi.servers\s*:\s*).*/\1$(params.restVillainsOpenapiServers)/" -i ./$(params.restVillainsKustomization)

      git add .
      git commit --allow-empty -m "Update quarkus.smallrye-openapi.servers"
      git push origin "$(params.gitRepositoryRevision)"
