---
apiVersion: opentelemetry.io/v1alpha1
kind: OpenTelemetryCollector
metadata:
  name: otel-collector
  namespace: {{ .Values.monitoringNamespace }}
  labels:
    # system: quarkus-super-heroes
    system: otel-collector
    name: otel-collector
    app: otel-collector
    role: monitoring
    app.kubernetes.io/part-of: monitoring
    app.openshift.io/runtime: opentelemetry
  annotations:
    app.openshift.io/connects-to: '[{"apiVersion":"jaegertracing.io/v1","kind":"Jaeger","name":"jaeger"}]'
spec:
  config: |
    receivers:
      otlp:
        protocols:
          grpc:
    exporters:
      otlp/jaeger:
        endpoint: jaeger-collector-headless.{{ .Values.monitoringNamespace }}.svc:4317
        tls:
          insecure: true
    processors:
      batch:
    extensions:
      health_check:
    service:
      extensions:
        - health_check
      pipelines:
        traces:
          receivers:
            - otlp
          processors:
            - batch
          exporters:
            - otlp/jaeger
